### PR TITLE
[fix] make sure that we don'T accidentially add the finalizing ; twice

### PR DESCRIPTION
**Pull request by chr-engwer**

### CODE REVIEW

**Comment by chr-engwer** [comment]
I ran the test-suite locally and it passes. I guess it is safe to merge.

**Comment by chr-engwer** [comment]
@FabioLuporini should I just merge? Or will you do this?

**Comment by FabioLuporini** [comment]
I'm gonna run it too and then I'll merge it. Does it also pass the Firedrake tests? 

Thanks Christian

**Comment by chr-engwer** [comment]
> I'm gonna run it too and then I'll merge it. Does it also pass the Firedrake tests? 

There was one failing test, but I discussed with others in the office
and we agreed that this is not the fault of my changes, but has some
other reason.

**Comment by FabioLuporini** [comment]
OK, thanks, merging.

**Pull request merged**
