### PR TITLE
vectorizer: Fix introduction of aligned(...)

### PR DESCRIPTION
**Pull request by FabioLuporini**
*** Maybe not yet ready for merge (read below) ***

Alignment qualifiers now appear in the code.

Still need to run the test suite. 

Let's however start talking about the following "problem":

The vectorizer doesn't like the following type of notation ``A[(j0 * 6) + j1][(k0 * 6) + k1] = ...``
In essence, to maximize the effectiveness of the vector code, it is fundamental that the base addresses of all LOAD/STORE instructions are aligned to multiples of the vector length. COFFEE attempts to achieve this through several transformations, including:
- padding
- data alignment
- loop bounds rounding

Padding and data alignment now look OK (modulo happy Travis), but the innermost loop is sometimes not rounded when instead it could actually be rounded (eg, by rounding the endpoint from 6 to 8 in case AVX is used). While most loops are properly rounded, the loop enclosing ``A[(j0 * 6) + j1][(k0 * 6) + k1] = ...`` is not: this is because COFFEE cannot determine whether the rounding pass will break the computation, as it doesn't know how to interpret array accesses when these are multidimensional functions.

The good news is that the code is anyway vectorizable -- it might just run a little slower than ideal as a remainder loop might be inserted, and executed with SSE instructions instead of AVX (or higher) instructions

### CODE REVIEW

**Comment by wence-** [comment]
I really hope this loop doesn't get executed with SSE, since if the rest is done with avx (for whatever reason), we'll get horrbile performance: switching from avx to sse incurs multiple 10s of cycles delay.

**Comment by miklos1** [comment]
> The vectorizer doesn't like the following type of notation `A[(j0 * 6) + j1][(k0 * 6) + k1] = ...`

**Comment by miklos1** [comment]
> The vectorizer doesn't like the following type of notation `A[(j0 * 6) + j1][(k0 * 6) + k1] = ...`

It's just an inline reshape. What would you do if it were `A[j0][j1][k0][k1] = ...` where 0 <= `j0` < 6 and 0 <= `k0` < 6?

**Comment by FabioLuporini** [comment]
> What would you do if it were A[j0][j1][k0][k1] = ... where 0 <= j0 < 6 and 0 <= k0 < 6?

you just care about the innermost dimension (k1)

> I really hope this loop doesn't get executed with SSE, since if the rest is done with avx (for whatever reason), we'll get horrbile performance: switching from avx to sse incurs multiple 10s of cycles delay.

your hope is well posed with the Intel compiler (I actually now remember that I had read this in the past): https://software.intel.com/en-us/articles/avoiding-avx-sse-transition-penalties
Read section 3.1. Not sure what happens with GCC. I guess pretty much the same thing.

**Comment by miklos1** [comment]
This cannot be merged yet as it breaks Firedrake.

**Comment by wence-** [comment]
This will soon become obsolete with new loopy codegen.

**Pull request closed without merging**
