### PR TITLE
Fix routine that minimises temporaries

### PR DESCRIPTION
**Pull request by FabioLuporini**

### CODE REVIEW

**Comment by wence-** [comment]
You'll need to update the tests to the new CountOccurences interface I think.

**Comment by wence-** [comment]
Oh no, linting!

**Comment by wence-** [comment]
Can you (and/or @alsgregory) formulate the code that creates the problem as a firedrake test so we don't regress?

**Comment by FabioLuporini** [comment]
Oh when I wrote "its interface" I just meant the wrapper in utils.py. The actual interface of the visitor has unchanged

**Comment by FabioLuporini** [comment]
Latest commit should have fixed linting

**Comment by FabioLuporini** [comment]
can we merge this?

**Comment by wence-** [comment]
Yes

**Comment by wence-** [comment]
@alsgregory Can you formulate your problem here as a test case for the firedrake test suite?

**Pull request merged**
