### PR TITLE
Log flops

### PR DESCRIPTION
**Pull request by wence-**
A few fixes for flop logging.

### CODE REVIEW

**Comment by FabioLuporini** [comment]
@wence : this init property that you added, where do you use it? is it in a branch in PyOP2? what I was referring to with the latest comment is the fact that we should rather use the lvalue and rvalue properties

**Comment by wence-** [comment]
In the `CountFlops` visitor, I ask a for loop for its size (which uses the init property of the iteration variable).  However, in the case that the iteration variable is not declared in the for loop, that currently doesn't exist because an `Assign` object has no init property.

**Comment by FabioLuporini** [comment]
Yes, but "now" (i.e., with that commit) both Decl and Assign have this {l,r}value property. Can you not just use it?

**Comment by wence-** [comment]
Oh, I see, probably.

**Comment by wence-** [comment]
I've now cherry picked that commit and added a few more tests.

**Comment by FabioLuporini** [comment]
OK, if they all pass, let's merge this.

**Comment by wence-** [comment]
Lint fail, have pushed a fix, hopefully this now works.

**Pull request merged**
