### PR TITLE
Log flops

### PR DESCRIPTION
**Pull request by wence-**
Add visitor to estimate the number of effective flops a tree performs

### CODE REVIEW

**Comment by FabioLuporini** [comment]
Makes sense. I think we could also add a simple wrapper function to utils.py so that one doesn't have to use the visitor directly to get the flop count.

**Comment by FabioLuporini** [comment]
Ah, wait. If a loops get vectorized, we should divide by the vector length the impact of *innermost* loops. Or we can return two numbers, the scalar flop count and the vector flop count. To get the vector length, you should use

**Comment by wence-** [comment]
Can you explain what you mean using an example.

**Comment by wence-** [comment]
IOW, I think I do this, whenever I hit a loop, I count the flops in the loop body and then multiply by the number of loop iterations (the size / increment).

So if we have:

```c
for ( i = 0; i < 16; i += 4 ) {
    _mm_add_pd(a, b);
}
```

Then I count each add_pd as 4 flops and multiply by 16 / 4 = 4, giving 16 flops.  Which I think is right.

**Comment by FabioLuporini** [comment]
That doesn't take into account autovectorization of scalar loops. Even if the loop increment is +=1, the loop could (should, is) autovectorized. Depending on whether you're using sse, avx, etc, the loop increments varies. The vector length (and so the autovectorized loop increment) is given by isa['dp_reg'] (double precision per vector register)

**Comment by wence-** [comment]
I don't care about "actual" flops in the compiled code.  I am counting "effective" flops.

**Comment by wence-** [comment]
In particular, I have NO WAY of knowing if the compiler has auto-vectorized the loop, so what am I meant to count?

**Comment by FabioLuporini** [comment]
if you want to estimate the gigaflops per seconds you do, which is what I think you want to do, I don't see how what you call effective flops would be useful.

**Comment by wence-** [comment]
Why not?  I count the number of flops I do, I divide by the time it took.  Lo and behold, "flop/s"

**Comment by FabioLuporini** [comment]
I meant "if vectorization is used"

**Comment by wence-** [comment]
So?  The effective flops are the number of double precision floating point operations I /would have had to do/ to get my answer.  I don't care how they executed.

**Comment by wence-** [comment]
To put it another way.  Doing four double precision floating point multiplies is, in my world, four double precision floating point operations, irrespective of whether it's compiled to four scalar instructions or one avx instruction.  You seem to be arguing for some other count.

**Comment by FabioLuporini** [comment]
Ah, forget it, makes sense. 

I thought we needed the actual number of vector operations to see how many vector operations we were doing so that we could compare it to the corresponding machine peak, but yes, this is not what usually one does

**Pull request merged**
